package org.innox.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.innox.pojo.BookTable;
import org.innox.pojo.BookTableExample;

public interface BookTableMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_table
     *
     * @mbg.generated Mon Apr 26 20:05:47 JST 2021
     */
    long countByExample(BookTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_table
     *
     * @mbg.generated Mon Apr 26 20:05:47 JST 2021
     */
    int deleteByExample(BookTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_table
     *
     * @mbg.generated Mon Apr 26 20:05:47 JST 2021
     */
    int deleteByPrimaryKey(Long bookId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_table
     *
     * @mbg.generated Mon Apr 26 20:05:47 JST 2021
     */
    int insert(BookTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_table
     *
     * @mbg.generated Mon Apr 26 20:05:47 JST 2021
     */
    int insertSelective(BookTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_table
     *
     * @mbg.generated Mon Apr 26 20:05:47 JST 2021
     */
    List<BookTable> selectByExample(BookTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_table
     *
     * @mbg.generated Mon Apr 26 20:05:47 JST 2021
     */
    BookTable selectByPrimaryKey(Long bookId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_table
     *
     * @mbg.generated Mon Apr 26 20:05:47 JST 2021
     */
    int updateByExampleSelective(@Param("record") BookTable record, @Param("example") BookTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_table
     *
     * @mbg.generated Mon Apr 26 20:05:47 JST 2021
     */
    int updateByExample(@Param("record") BookTable record, @Param("example") BookTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_table
     *
     * @mbg.generated Mon Apr 26 20:05:47 JST 2021
     */
    int updateByPrimaryKeySelective(BookTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_table
     *
     * @mbg.generated Mon Apr 26 20:05:47 JST 2021
     */
    int updateByPrimaryKey(BookTable record);
}