package org.innox.mapper;

import org.innox.pojo.BookTable;

public interface BookTableMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_table
     *
     * @mbg.generated Mon Apr 19 03:23:44 JST 2021
     */
    int deleteByPrimaryKey(Long bookId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_table
     *
     * @mbg.generated Mon Apr 19 03:23:44 JST 2021
     */
    int insert(BookTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_table
     *
     * @mbg.generated Mon Apr 19 03:23:44 JST 2021
     */
    int insertSelective(BookTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_table
     *
     * @mbg.generated Mon Apr 19 03:23:44 JST 2021
     */
    BookTable selectByPrimaryKey(Long bookId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_table
     *
     * @mbg.generated Mon Apr 19 03:23:44 JST 2021
     */
    int updateByPrimaryKeySelective(BookTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_table
     *
     * @mbg.generated Mon Apr 19 03:23:44 JST 2021
     */
    int updateByPrimaryKey(BookTable record);
}