package org.innox.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.innox.pojo.CodeTable;
import org.innox.pojo.CodeTableExample;

public interface CodeTableMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table code_table
     *
     * @mbg.generated Mon Apr 26 20:05:47 JST 2021
     */
    long countByExample(CodeTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table code_table
     *
     * @mbg.generated Mon Apr 26 20:05:47 JST 2021
     */
    int deleteByExample(CodeTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table code_table
     *
     * @mbg.generated Mon Apr 26 20:05:47 JST 2021
     */
    int deleteByPrimaryKey(Long codeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table code_table
     *
     * @mbg.generated Mon Apr 26 20:05:47 JST 2021
     */
    int insert(CodeTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table code_table
     *
     * @mbg.generated Mon Apr 26 20:05:47 JST 2021
     */
    int insertSelective(CodeTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table code_table
     *
     * @mbg.generated Mon Apr 26 20:05:47 JST 2021
     */
    List<CodeTable> selectByExample(CodeTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table code_table
     *
     * @mbg.generated Mon Apr 26 20:05:47 JST 2021
     */
    CodeTable selectByPrimaryKey(Long codeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table code_table
     *
     * @mbg.generated Mon Apr 26 20:05:47 JST 2021
     */
    int updateByExampleSelective(@Param("record") CodeTable record, @Param("example") CodeTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table code_table
     *
     * @mbg.generated Mon Apr 26 20:05:47 JST 2021
     */
    int updateByExample(@Param("record") CodeTable record, @Param("example") CodeTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table code_table
     *
     * @mbg.generated Mon Apr 26 20:05:47 JST 2021
     */
    int updateByPrimaryKeySelective(CodeTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table code_table
     *
     * @mbg.generated Mon Apr 26 20:05:47 JST 2021
     */
    int updateByPrimaryKey(CodeTable record);
}