package org.innox.mapper;

import org.innox.pojo.FavouritesTable;

public interface FavouritesTableMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favourites_table
     *
     * @mbg.generated Mon Apr 19 03:23:44 JST 2021
     */
    int deleteByPrimaryKey(Integer favouritesId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favourites_table
     *
     * @mbg.generated Mon Apr 19 03:23:44 JST 2021
     */
    int insert(FavouritesTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favourites_table
     *
     * @mbg.generated Mon Apr 19 03:23:44 JST 2021
     */
    int insertSelective(FavouritesTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favourites_table
     *
     * @mbg.generated Mon Apr 19 03:23:44 JST 2021
     */
    FavouritesTable selectByPrimaryKey(Integer favouritesId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favourites_table
     *
     * @mbg.generated Mon Apr 19 03:23:44 JST 2021
     */
    int updateByPrimaryKeySelective(FavouritesTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favourites_table
     *
     * @mbg.generated Mon Apr 19 03:23:44 JST 2021
     */
    int updateByPrimaryKey(FavouritesTable record);
}