package org.innox.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.innox.pojo.FavouritesTable;
import org.innox.pojo.FavouritesTableExample;

public interface FavouritesTableMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favourites_table
     *
     * @mbg.generated Wed May 12 16:37:06 JST 2021
     */
    long countByExample(FavouritesTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favourites_table
     *
     * @mbg.generated Wed May 12 16:37:06 JST 2021
     */
    int deleteByExample(FavouritesTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favourites_table
     *
     * @mbg.generated Wed May 12 16:37:06 JST 2021
     */
    int deleteByPrimaryKey(Long favouritesId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favourites_table
     *
     * @mbg.generated Wed May 12 16:37:06 JST 2021
     */
    int insert(FavouritesTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favourites_table
     *
     * @mbg.generated Wed May 12 16:37:06 JST 2021
     */
    int insertSelective(FavouritesTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favourites_table
     *
     * @mbg.generated Wed May 12 16:37:06 JST 2021
     */
    List<FavouritesTable> selectByExample(FavouritesTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favourites_table
     *
     * @mbg.generated Wed May 12 16:37:06 JST 2021
     */
    FavouritesTable selectByPrimaryKey(Long favouritesId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favourites_table
     *
     * @mbg.generated Wed May 12 16:37:06 JST 2021
     */
    int updateByExampleSelective(@Param("record") FavouritesTable record, @Param("example") FavouritesTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favourites_table
     *
     * @mbg.generated Wed May 12 16:37:06 JST 2021
     */
    int updateByExample(@Param("record") FavouritesTable record, @Param("example") FavouritesTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favourites_table
     *
     * @mbg.generated Wed May 12 16:37:06 JST 2021
     */
    int updateByPrimaryKeySelective(FavouritesTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favourites_table
     *
     * @mbg.generated Wed May 12 16:37:06 JST 2021
     */
    int updateByPrimaryKey(FavouritesTable record);
}