package org.innox.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.innox.pojo.GrammerTable;
import org.innox.pojo.GrammerTableExample;

public interface GrammerTableMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grammer_table
     *
     * @mbg.generated Wed May 12 16:37:06 JST 2021
     */
    long countByExample(GrammerTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grammer_table
     *
     * @mbg.generated Wed May 12 16:37:06 JST 2021
     */
    int deleteByExample(GrammerTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grammer_table
     *
     * @mbg.generated Wed May 12 16:37:06 JST 2021
     */
    int deleteByPrimaryKey(Long grammerId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grammer_table
     *
     * @mbg.generated Wed May 12 16:37:06 JST 2021
     */
    int insert(GrammerTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grammer_table
     *
     * @mbg.generated Wed May 12 16:37:06 JST 2021
     */
    int insertSelective(GrammerTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grammer_table
     *
     * @mbg.generated Wed May 12 16:37:06 JST 2021
     */
    List<GrammerTable> selectByExample(GrammerTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grammer_table
     *
     * @mbg.generated Wed May 12 16:37:06 JST 2021
     */
    GrammerTable selectByPrimaryKey(Long grammerId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grammer_table
     *
     * @mbg.generated Wed May 12 16:37:06 JST 2021
     */
    int updateByExampleSelective(@Param("record") GrammerTable record, @Param("example") GrammerTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grammer_table
     *
     * @mbg.generated Wed May 12 16:37:06 JST 2021
     */
    int updateByExample(@Param("record") GrammerTable record, @Param("example") GrammerTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grammer_table
     *
     * @mbg.generated Wed May 12 16:37:06 JST 2021
     */
    int updateByPrimaryKeySelective(GrammerTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grammer_table
     *
     * @mbg.generated Wed May 12 16:37:06 JST 2021
     */
    int updateByPrimaryKey(GrammerTable record);
}