package org.innox.mapper;

import org.innox.pojo.GrammarTable;

public interface GrammarTableMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grammar_table
     *
     * @mbg.generated Mon Apr 19 03:23:44 JST 2021
     */
    int deleteByPrimaryKey(Long grammarId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grammar_table
     *
     * @mbg.generated Mon Apr 19 03:23:44 JST 2021
     */
    int insert(GrammarTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grammar_table
     *
     * @mbg.generated Mon Apr 19 03:23:44 JST 2021
     */
    int insertSelective(GrammarTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grammar_table
     *
     * @mbg.generated Mon Apr 19 03:23:44 JST 2021
     */
    GrammarTable selectByPrimaryKey(Long grammarId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grammar_table
     *
     * @mbg.generated Mon Apr 19 03:23:44 JST 2021
     */
    int updateByPrimaryKeySelective(GrammarTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grammar_table
     *
     * @mbg.generated Mon Apr 19 03:23:44 JST 2021
     */
    int updateByPrimaryKey(GrammarTable record);
}