package org.innox.mapper;

import org.innox.pojo.LessonTable;
import org.innox.pojo.LessonTableKey;

public interface LessonTableMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lesson_table
     *
     * @mbg.generated Mon Apr 19 03:23:44 JST 2021
     */
    int deleteByPrimaryKey(LessonTableKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lesson_table
     *
     * @mbg.generated Mon Apr 19 03:23:44 JST 2021
     */
    int insert(LessonTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lesson_table
     *
     * @mbg.generated Mon Apr 19 03:23:44 JST 2021
     */
    int insertSelective(LessonTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lesson_table
     *
     * @mbg.generated Mon Apr 19 03:23:44 JST 2021
     */
    LessonTable selectByPrimaryKey(LessonTableKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lesson_table
     *
     * @mbg.generated Mon Apr 19 03:23:44 JST 2021
     */
    int updateByPrimaryKeySelective(LessonTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lesson_table
     *
     * @mbg.generated Mon Apr 19 03:23:44 JST 2021
     */
    int updateByPrimaryKey(LessonTable record);
}