package org.innox.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.innox.pojo.PhraseTable;
import org.innox.pojo.PhraseTableExample;

public interface PhraseTableMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phrase_table
     *
     * @mbg.generated Wed May 12 16:37:06 JST 2021
     */
    long countByExample(PhraseTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phrase_table
     *
     * @mbg.generated Wed May 12 16:37:06 JST 2021
     */
    int deleteByExample(PhraseTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phrase_table
     *
     * @mbg.generated Wed May 12 16:37:06 JST 2021
     */
    int deleteByPrimaryKey(Long phraseId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phrase_table
     *
     * @mbg.generated Wed May 12 16:37:06 JST 2021
     */
    int insert(PhraseTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phrase_table
     *
     * @mbg.generated Wed May 12 16:37:06 JST 2021
     */
    int insertSelective(PhraseTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phrase_table
     *
     * @mbg.generated Wed May 12 16:37:06 JST 2021
     */
    List<PhraseTable> selectByExample(PhraseTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phrase_table
     *
     * @mbg.generated Wed May 12 16:37:06 JST 2021
     */
    PhraseTable selectByPrimaryKey(Long phraseId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phrase_table
     *
     * @mbg.generated Wed May 12 16:37:06 JST 2021
     */
    int updateByExampleSelective(@Param("record") PhraseTable record, @Param("example") PhraseTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phrase_table
     *
     * @mbg.generated Wed May 12 16:37:06 JST 2021
     */
    int updateByExample(@Param("record") PhraseTable record, @Param("example") PhraseTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phrase_table
     *
     * @mbg.generated Wed May 12 16:37:06 JST 2021
     */
    int updateByPrimaryKeySelective(PhraseTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phrase_table
     *
     * @mbg.generated Wed May 12 16:37:06 JST 2021
     */
    int updateByPrimaryKey(PhraseTable record);
}