package org.innox.mapper;

import org.innox.pojo.SentencePhraseTable;
import org.innox.pojo.SentencePhraseTableKey;

public interface SentencePhraseTableMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sentence_phrase_table
     *
     * @mbg.generated Mon Apr 19 03:23:44 JST 2021
     */
    int deleteByPrimaryKey(SentencePhraseTableKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sentence_phrase_table
     *
     * @mbg.generated Mon Apr 19 03:23:44 JST 2021
     */
    int insert(SentencePhraseTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sentence_phrase_table
     *
     * @mbg.generated Mon Apr 19 03:23:44 JST 2021
     */
    int insertSelective(SentencePhraseTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sentence_phrase_table
     *
     * @mbg.generated Mon Apr 19 03:23:44 JST 2021
     */
    SentencePhraseTable selectByPrimaryKey(SentencePhraseTableKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sentence_phrase_table
     *
     * @mbg.generated Mon Apr 19 03:23:44 JST 2021
     */
    int updateByPrimaryKeySelective(SentencePhraseTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sentence_phrase_table
     *
     * @mbg.generated Mon Apr 19 03:23:44 JST 2021
     */
    int updateByPrimaryKey(SentencePhraseTable record);
}