package org.innox.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.innox.pojo.SentenceWordTable;
import org.innox.pojo.SentenceWordTableExample;
import org.innox.pojo.SentenceWordTableKey;

public interface SentenceWordTableMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sentence_word_table
     *
     * @mbg.generated Mon Apr 26 20:05:47 JST 2021
     */
    long countByExample(SentenceWordTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sentence_word_table
     *
     * @mbg.generated Mon Apr 26 20:05:47 JST 2021
     */
    int deleteByExample(SentenceWordTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sentence_word_table
     *
     * @mbg.generated Mon Apr 26 20:05:47 JST 2021
     */
    int deleteByPrimaryKey(SentenceWordTableKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sentence_word_table
     *
     * @mbg.generated Mon Apr 26 20:05:47 JST 2021
     */
    int insert(SentenceWordTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sentence_word_table
     *
     * @mbg.generated Mon Apr 26 20:05:47 JST 2021
     */
    int insertSelective(SentenceWordTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sentence_word_table
     *
     * @mbg.generated Mon Apr 26 20:05:47 JST 2021
     */
    List<SentenceWordTable> selectByExample(SentenceWordTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sentence_word_table
     *
     * @mbg.generated Mon Apr 26 20:05:47 JST 2021
     */
    SentenceWordTable selectByPrimaryKey(SentenceWordTableKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sentence_word_table
     *
     * @mbg.generated Mon Apr 26 20:05:47 JST 2021
     */
    int updateByExampleSelective(@Param("record") SentenceWordTable record, @Param("example") SentenceWordTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sentence_word_table
     *
     * @mbg.generated Mon Apr 26 20:05:47 JST 2021
     */
    int updateByExample(@Param("record") SentenceWordTable record, @Param("example") SentenceWordTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sentence_word_table
     *
     * @mbg.generated Mon Apr 26 20:05:47 JST 2021
     */
    int updateByPrimaryKeySelective(SentenceWordTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sentence_word_table
     *
     * @mbg.generated Mon Apr 26 20:05:47 JST 2021
     */
    int updateByPrimaryKey(SentenceWordTable record);
}