package org.innox.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.innox.pojo.SentenceTable;
import org.innox.pojo.SentenceTableExample;

public interface SentenceTableMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sentence_table
     *
     * @mbg.generated Mon May 24 13:50:34 JST 2021
     */
    long countByExample(SentenceTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sentence_table
     *
     * @mbg.generated Mon May 24 13:50:34 JST 2021
     */
    int deleteByExample(SentenceTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sentence_table
     *
     * @mbg.generated Mon May 24 13:50:34 JST 2021
     */
    int deleteByPrimaryKey(Long sentenceSeq);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sentence_table
     *
     * @mbg.generated Mon May 24 13:50:34 JST 2021
     */
    int insert(SentenceTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sentence_table
     *
     * @mbg.generated Mon May 24 13:50:34 JST 2021
     */
    int insertSelective(SentenceTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sentence_table
     *
     * @mbg.generated Mon May 24 13:50:34 JST 2021
     */
    List<SentenceTable> selectByExample(SentenceTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sentence_table
     *
     * @mbg.generated Mon May 24 13:50:34 JST 2021
     */
    SentenceTable selectByPrimaryKey(Long sentenceSeq);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sentence_table
     *
     * @mbg.generated Mon May 24 13:50:34 JST 2021
     */
    int updateByExampleSelective(@Param("record") SentenceTable record, @Param("example") SentenceTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sentence_table
     *
     * @mbg.generated Mon May 24 13:50:34 JST 2021
     */
    int updateByExample(@Param("record") SentenceTable record, @Param("example") SentenceTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sentence_table
     *
     * @mbg.generated Mon May 24 13:50:34 JST 2021
     */
    int updateByPrimaryKeySelective(SentenceTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sentence_table
     *
     * @mbg.generated Mon May 24 13:50:34 JST 2021
     */
    int updateByPrimaryKey(SentenceTable record);
}