package org.innox.mapper;

import org.innox.pojo.SentenceTable;

public interface SentenceTableMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sentence_table
     *
     * @mbg.generated Mon Apr 19 03:23:44 JST 2021
     */
    int deleteByPrimaryKey(Long sentenceSeq);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sentence_table
     *
     * @mbg.generated Mon Apr 19 03:23:44 JST 2021
     */
    int insert(SentenceTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sentence_table
     *
     * @mbg.generated Mon Apr 19 03:23:44 JST 2021
     */
    int insertSelective(SentenceTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sentence_table
     *
     * @mbg.generated Mon Apr 19 03:23:44 JST 2021
     */
    SentenceTable selectByPrimaryKey(Long sentenceSeq);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sentence_table
     *
     * @mbg.generated Mon Apr 19 03:23:44 JST 2021
     */
    int updateByPrimaryKeySelective(SentenceTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sentence_table
     *
     * @mbg.generated Mon Apr 19 03:23:44 JST 2021
     */
    int updateByPrimaryKey(SentenceTable record);
}