package org.innox.mapper;

import org.innox.pojo.SentenceGrammerTable;
import org.innox.pojo.SentenceGrammerTableKey;

public interface SentenceGrammerTableMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sentence_grammer_table
     *
     * @mbg.generated Mon Apr 19 03:23:44 JST 2021
     */
    int deleteByPrimaryKey(SentenceGrammerTableKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sentence_grammer_table
     *
     * @mbg.generated Mon Apr 19 03:23:44 JST 2021
     */
    int insert(SentenceGrammerTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sentence_grammer_table
     *
     * @mbg.generated Mon Apr 19 03:23:44 JST 2021
     */
    int insertSelective(SentenceGrammerTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sentence_grammer_table
     *
     * @mbg.generated Mon Apr 19 03:23:44 JST 2021
     */
    SentenceGrammerTable selectByPrimaryKey(SentenceGrammerTableKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sentence_grammer_table
     *
     * @mbg.generated Mon Apr 19 03:23:44 JST 2021
     */
    int updateByPrimaryKeySelective(SentenceGrammerTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sentence_grammer_table
     *
     * @mbg.generated Mon Apr 19 03:23:44 JST 2021
     */
    int updateByPrimaryKey(SentenceGrammerTable record);
}