package org.innox.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.innox.pojo.SentenceGrammerTable;
import org.innox.pojo.SentenceGrammerTableExample;
import org.innox.pojo.SentenceGrammerTableKey;

public interface SentenceGrammerTableMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sentence_grammer_table
     *
     * @mbg.generated Wed May 12 16:37:06 JST 2021
     */
    long countByExample(SentenceGrammerTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sentence_grammer_table
     *
     * @mbg.generated Wed May 12 16:37:06 JST 2021
     */
    int deleteByExample(SentenceGrammerTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sentence_grammer_table
     *
     * @mbg.generated Wed May 12 16:37:06 JST 2021
     */
    int deleteByPrimaryKey(SentenceGrammerTableKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sentence_grammer_table
     *
     * @mbg.generated Wed May 12 16:37:06 JST 2021
     */
    int insert(SentenceGrammerTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sentence_grammer_table
     *
     * @mbg.generated Wed May 12 16:37:06 JST 2021
     */
    int insertSelective(SentenceGrammerTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sentence_grammer_table
     *
     * @mbg.generated Wed May 12 16:37:06 JST 2021
     */
    List<SentenceGrammerTable> selectByExample(SentenceGrammerTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sentence_grammer_table
     *
     * @mbg.generated Wed May 12 16:37:06 JST 2021
     */
    SentenceGrammerTable selectByPrimaryKey(SentenceGrammerTableKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sentence_grammer_table
     *
     * @mbg.generated Wed May 12 16:37:06 JST 2021
     */
    int updateByExampleSelective(@Param("record") SentenceGrammerTable record, @Param("example") SentenceGrammerTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sentence_grammer_table
     *
     * @mbg.generated Wed May 12 16:37:06 JST 2021
     */
    int updateByExample(@Param("record") SentenceGrammerTable record, @Param("example") SentenceGrammerTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sentence_grammer_table
     *
     * @mbg.generated Wed May 12 16:37:06 JST 2021
     */
    int updateByPrimaryKeySelective(SentenceGrammerTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sentence_grammer_table
     *
     * @mbg.generated Wed May 12 16:37:06 JST 2021
     */
    int updateByPrimaryKey(SentenceGrammerTable record);
}