package org.innox.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.innox.pojo.UserPracticeHistory;
import org.innox.pojo.UserPracticeHistoryExample;

public interface UserPracticeHistoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_practice_history
     *
     * @mbg.generated Mon May 24 13:50:34 JST 2021
     */
    long countByExample(UserPracticeHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_practice_history
     *
     * @mbg.generated Mon May 24 13:50:34 JST 2021
     */
    int deleteByExample(UserPracticeHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_practice_history
     *
     * @mbg.generated Mon May 24 13:50:34 JST 2021
     */
    int deleteByPrimaryKey(Long historyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_practice_history
     *
     * @mbg.generated Mon May 24 13:50:34 JST 2021
     */
    int insert(UserPracticeHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_practice_history
     *
     * @mbg.generated Mon May 24 13:50:34 JST 2021
     */
    int insertSelective(UserPracticeHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_practice_history
     *
     * @mbg.generated Mon May 24 13:50:34 JST 2021
     */
    List<UserPracticeHistory> selectByExample(UserPracticeHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_practice_history
     *
     * @mbg.generated Mon May 24 13:50:34 JST 2021
     */
    UserPracticeHistory selectByPrimaryKey(Long historyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_practice_history
     *
     * @mbg.generated Mon May 24 13:50:34 JST 2021
     */
    int updateByExampleSelective(@Param("record") UserPracticeHistory record, @Param("example") UserPracticeHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_practice_history
     *
     * @mbg.generated Mon May 24 13:50:34 JST 2021
     */
    int updateByExample(@Param("record") UserPracticeHistory record, @Param("example") UserPracticeHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_practice_history
     *
     * @mbg.generated Mon May 24 13:50:34 JST 2021
     */
    int updateByPrimaryKeySelective(UserPracticeHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_practice_history
     *
     * @mbg.generated Mon May 24 13:50:34 JST 2021
     */
    int updateByPrimaryKey(UserPracticeHistory record);
}