package org.innox.mapper;

import org.innox.pojo.UserPracticeHistory;

public interface UserPracticeHistoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_practice_history
     *
     * @mbg.generated Mon Apr 19 03:23:44 JST 2021
     */
    int deleteByPrimaryKey(Integer historyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_practice_history
     *
     * @mbg.generated Mon Apr 19 03:23:44 JST 2021
     */
    int insert(UserPracticeHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_practice_history
     *
     * @mbg.generated Mon Apr 19 03:23:44 JST 2021
     */
    int insertSelective(UserPracticeHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_practice_history
     *
     * @mbg.generated Mon Apr 19 03:23:44 JST 2021
     */
    UserPracticeHistory selectByPrimaryKey(Integer historyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_practice_history
     *
     * @mbg.generated Mon Apr 19 03:23:44 JST 2021
     */
    int updateByPrimaryKeySelective(UserPracticeHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_practice_history
     *
     * @mbg.generated Mon Apr 19 03:23:44 JST 2021
     */
    int updateByPrimaryKey(UserPracticeHistory record);
}