package org.innox.mapper;

import org.innox.pojo.WordTable;

public interface WordTableMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table word_table
     *
     * @mbg.generated Mon Apr 19 03:23:44 JST 2021
     */
    int deleteByPrimaryKey(Long wordId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table word_table
     *
     * @mbg.generated Mon Apr 19 03:23:44 JST 2021
     */
    int insert(WordTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table word_table
     *
     * @mbg.generated Mon Apr 19 03:23:44 JST 2021
     */
    int insertSelective(WordTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table word_table
     *
     * @mbg.generated Mon Apr 19 03:23:44 JST 2021
     */
    WordTable selectByPrimaryKey(Long wordId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table word_table
     *
     * @mbg.generated Mon Apr 19 03:23:44 JST 2021
     */
    int updateByPrimaryKeySelective(WordTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table word_table
     *
     * @mbg.generated Mon Apr 19 03:23:44 JST 2021
     */
    int updateByPrimaryKey(WordTable record);
}