package org.innox.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.innox.pojo.WordTable;
import org.innox.pojo.WordTableExample;

public interface WordTableMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table word_table
     *
     * @mbg.generated Mon Apr 26 20:05:47 JST 2021
     */
    long countByExample(WordTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table word_table
     *
     * @mbg.generated Mon Apr 26 20:05:47 JST 2021
     */
    int deleteByExample(WordTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table word_table
     *
     * @mbg.generated Mon Apr 26 20:05:47 JST 2021
     */
    int deleteByPrimaryKey(Long wordId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table word_table
     *
     * @mbg.generated Mon Apr 26 20:05:47 JST 2021
     */
    int insert(WordTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table word_table
     *
     * @mbg.generated Mon Apr 26 20:05:47 JST 2021
     */
    int insertSelective(WordTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table word_table
     *
     * @mbg.generated Mon Apr 26 20:05:47 JST 2021
     */
    List<WordTable> selectByExample(WordTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table word_table
     *
     * @mbg.generated Mon Apr 26 20:05:47 JST 2021
     */
    WordTable selectByPrimaryKey(Long wordId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table word_table
     *
     * @mbg.generated Mon Apr 26 20:05:47 JST 2021
     */
    int updateByExampleSelective(@Param("record") WordTable record, @Param("example") WordTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table word_table
     *
     * @mbg.generated Mon Apr 26 20:05:47 JST 2021
     */
    int updateByExample(@Param("record") WordTable record, @Param("example") WordTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table word_table
     *
     * @mbg.generated Mon Apr 26 20:05:47 JST 2021
     */
    int updateByPrimaryKeySelective(WordTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table word_table
     *
     * @mbg.generated Mon Apr 26 20:05:47 JST 2021
     */
    int updateByPrimaryKey(WordTable record);
}