package org.innox.pojo;

import java.util.Date;

public class BookTable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_table.book_id
     *
     * @mbg.generated Mon May 24 13:50:34 JST 2021
     */
    private Long bookId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_table.book_name
     *
     * @mbg.generated Mon May 24 13:50:34 JST 2021
     */
    private String bookName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_table.description
     *
     * @mbg.generated Mon May 24 13:50:34 JST 2021
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_table.creater
     *
     * @mbg.generated Mon May 24 13:50:34 JST 2021
     */
    private String creater;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_table.create_time
     *
     * @mbg.generated Mon May 24 13:50:34 JST 2021
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_table.updater
     *
     * @mbg.generated Mon May 24 13:50:34 JST 2021
     */
    private String updater;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_table.update_time
     *
     * @mbg.generated Mon May 24 13:50:34 JST 2021
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_table.book_id
     *
     * @return the value of book_table.book_id
     *
     * @mbg.generated Mon May 24 13:50:34 JST 2021
     */
    public Long getBookId() {
        return bookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_table.book_id
     *
     * @param bookId the value for book_table.book_id
     *
     * @mbg.generated Mon May 24 13:50:34 JST 2021
     */
    public void setBookId(Long bookId) {
        this.bookId = bookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_table.book_name
     *
     * @return the value of book_table.book_name
     *
     * @mbg.generated Mon May 24 13:50:34 JST 2021
     */
    public String getBookName() {
        return bookName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_table.book_name
     *
     * @param bookName the value for book_table.book_name
     *
     * @mbg.generated Mon May 24 13:50:34 JST 2021
     */
    public void setBookName(String bookName) {
        this.bookName = bookName == null ? null : bookName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_table.description
     *
     * @return the value of book_table.description
     *
     * @mbg.generated Mon May 24 13:50:34 JST 2021
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_table.description
     *
     * @param description the value for book_table.description
     *
     * @mbg.generated Mon May 24 13:50:34 JST 2021
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_table.creater
     *
     * @return the value of book_table.creater
     *
     * @mbg.generated Mon May 24 13:50:34 JST 2021
     */
    public String getCreater() {
        return creater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_table.creater
     *
     * @param creater the value for book_table.creater
     *
     * @mbg.generated Mon May 24 13:50:34 JST 2021
     */
    public void setCreater(String creater) {
        this.creater = creater == null ? null : creater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_table.create_time
     *
     * @return the value of book_table.create_time
     *
     * @mbg.generated Mon May 24 13:50:34 JST 2021
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_table.create_time
     *
     * @param createTime the value for book_table.create_time
     *
     * @mbg.generated Mon May 24 13:50:34 JST 2021
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_table.updater
     *
     * @return the value of book_table.updater
     *
     * @mbg.generated Mon May 24 13:50:34 JST 2021
     */
    public String getUpdater() {
        return updater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_table.updater
     *
     * @param updater the value for book_table.updater
     *
     * @mbg.generated Mon May 24 13:50:34 JST 2021
     */
    public void setUpdater(String updater) {
        this.updater = updater == null ? null : updater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_table.update_time
     *
     * @return the value of book_table.update_time
     *
     * @mbg.generated Mon May 24 13:50:34 JST 2021
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_table.update_time
     *
     * @param updateTime the value for book_table.update_time
     *
     * @mbg.generated Mon May 24 13:50:34 JST 2021
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}