package org.innox.pojo;

public class CodeTable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column code_table.code_id
     *
     * @mbg.generated Mon May 24 13:50:34 JST 2021
     */
    private Long codeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column code_table.code_no
     *
     * @mbg.generated Mon May 24 13:50:34 JST 2021
     */
    private String codeNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column code_table.code_item
     *
     * @mbg.generated Mon May 24 13:50:34 JST 2021
     */
    private String codeItem;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column code_table.description
     *
     * @mbg.generated Mon May 24 13:50:34 JST 2021
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column code_table.code_id
     *
     * @return the value of code_table.code_id
     *
     * @mbg.generated Mon May 24 13:50:34 JST 2021
     */
    public Long getCodeId() {
        return codeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column code_table.code_id
     *
     * @param codeId the value for code_table.code_id
     *
     * @mbg.generated Mon May 24 13:50:34 JST 2021
     */
    public void setCodeId(Long codeId) {
        this.codeId = codeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column code_table.code_no
     *
     * @return the value of code_table.code_no
     *
     * @mbg.generated Mon May 24 13:50:34 JST 2021
     */
    public String getCodeNo() {
        return codeNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column code_table.code_no
     *
     * @param codeNo the value for code_table.code_no
     *
     * @mbg.generated Mon May 24 13:50:34 JST 2021
     */
    public void setCodeNo(String codeNo) {
        this.codeNo = codeNo == null ? null : codeNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column code_table.code_item
     *
     * @return the value of code_table.code_item
     *
     * @mbg.generated Mon May 24 13:50:34 JST 2021
     */
    public String getCodeItem() {
        return codeItem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column code_table.code_item
     *
     * @param codeItem the value for code_table.code_item
     *
     * @mbg.generated Mon May 24 13:50:34 JST 2021
     */
    public void setCodeItem(String codeItem) {
        this.codeItem = codeItem == null ? null : codeItem.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column code_table.description
     *
     * @return the value of code_table.description
     *
     * @mbg.generated Mon May 24 13:50:34 JST 2021
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column code_table.description
     *
     * @param description the value for code_table.description
     *
     * @mbg.generated Mon May 24 13:50:34 JST 2021
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}