package org.innox.pojo;

import java.util.Date;

public class FavouritesTable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column favourites_table.favourites_id
     *
     * @mbg.generated Mon May 24 13:50:34 JST 2021
     */
    private Long favouritesId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column favourites_table.user_id
     *
     * @mbg.generated Mon May 24 13:50:34 JST 2021
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column favourites_table.record_id
     *
     * @mbg.generated Mon May 24 13:50:34 JST 2021
     */
    private Object recordId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column favourites_table.creater
     *
     * @mbg.generated Mon May 24 13:50:34 JST 2021
     */
    private String creater;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column favourites_table.create_time
     *
     * @mbg.generated Mon May 24 13:50:34 JST 2021
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column favourites_table.updater
     *
     * @mbg.generated Mon May 24 13:50:34 JST 2021
     */
    private String updater;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column favourites_table.update_time
     *
     * @mbg.generated Mon May 24 13:50:34 JST 2021
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column favourites_table.favourites_id
     *
     * @return the value of favourites_table.favourites_id
     *
     * @mbg.generated Mon May 24 13:50:34 JST 2021
     */
    public Long getFavouritesId() {
        return favouritesId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column favourites_table.favourites_id
     *
     * @param favouritesId the value for favourites_table.favourites_id
     *
     * @mbg.generated Mon May 24 13:50:34 JST 2021
     */
    public void setFavouritesId(Long favouritesId) {
        this.favouritesId = favouritesId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column favourites_table.user_id
     *
     * @return the value of favourites_table.user_id
     *
     * @mbg.generated Mon May 24 13:50:34 JST 2021
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column favourites_table.user_id
     *
     * @param userId the value for favourites_table.user_id
     *
     * @mbg.generated Mon May 24 13:50:34 JST 2021
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column favourites_table.record_id
     *
     * @return the value of favourites_table.record_id
     *
     * @mbg.generated Mon May 24 13:50:34 JST 2021
     */
    public Object getRecordId() {
        return recordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column favourites_table.record_id
     *
     * @param recordId the value for favourites_table.record_id
     *
     * @mbg.generated Mon May 24 13:50:34 JST 2021
     */
    public void setRecordId(Object recordId) {
        this.recordId = recordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column favourites_table.creater
     *
     * @return the value of favourites_table.creater
     *
     * @mbg.generated Mon May 24 13:50:34 JST 2021
     */
    public String getCreater() {
        return creater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column favourites_table.creater
     *
     * @param creater the value for favourites_table.creater
     *
     * @mbg.generated Mon May 24 13:50:34 JST 2021
     */
    public void setCreater(String creater) {
        this.creater = creater == null ? null : creater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column favourites_table.create_time
     *
     * @return the value of favourites_table.create_time
     *
     * @mbg.generated Mon May 24 13:50:34 JST 2021
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column favourites_table.create_time
     *
     * @param createTime the value for favourites_table.create_time
     *
     * @mbg.generated Mon May 24 13:50:34 JST 2021
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column favourites_table.updater
     *
     * @return the value of favourites_table.updater
     *
     * @mbg.generated Mon May 24 13:50:34 JST 2021
     */
    public String getUpdater() {
        return updater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column favourites_table.updater
     *
     * @param updater the value for favourites_table.updater
     *
     * @mbg.generated Mon May 24 13:50:34 JST 2021
     */
    public void setUpdater(String updater) {
        this.updater = updater == null ? null : updater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column favourites_table.update_time
     *
     * @return the value of favourites_table.update_time
     *
     * @mbg.generated Mon May 24 13:50:34 JST 2021
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column favourites_table.update_time
     *
     * @param updateTime the value for favourites_table.update_time
     *
     * @mbg.generated Mon May 24 13:50:34 JST 2021
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}