package org.innox.pojo;

import java.util.Date;

public class GrammarTable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grammar_table.grammar_id
     *
     * @mbg.generated Mon Apr 19 03:23:44 JST 2021
     */
    private Long grammarId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grammar_table.grammer_title
     *
     * @mbg.generated Mon Apr 19 03:23:44 JST 2021
     */
    private String grammerTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grammar_table.grammer
     *
     * @mbg.generated Mon Apr 19 03:23:44 JST 2021
     */
    private String grammer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grammar_table.description
     *
     * @mbg.generated Mon Apr 19 03:23:44 JST 2021
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grammar_table.creater
     *
     * @mbg.generated Mon Apr 19 03:23:44 JST 2021
     */
    private String creater;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grammar_table.create_time
     *
     * @mbg.generated Mon Apr 19 03:23:44 JST 2021
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grammar_table.updater
     *
     * @mbg.generated Mon Apr 19 03:23:44 JST 2021
     */
    private String updater;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grammar_table.update_time
     *
     * @mbg.generated Mon Apr 19 03:23:44 JST 2021
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grammar_table.grammar_id
     *
     * @return the value of grammar_table.grammar_id
     *
     * @mbg.generated Mon Apr 19 03:23:44 JST 2021
     */
    public Long getGrammarId() {
        return grammarId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grammar_table.grammar_id
     *
     * @param grammarId the value for grammar_table.grammar_id
     *
     * @mbg.generated Mon Apr 19 03:23:44 JST 2021
     */
    public void setGrammarId(Long grammarId) {
        this.grammarId = grammarId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grammar_table.grammer_title
     *
     * @return the value of grammar_table.grammer_title
     *
     * @mbg.generated Mon Apr 19 03:23:44 JST 2021
     */
    public String getGrammerTitle() {
        return grammerTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grammar_table.grammer_title
     *
     * @param grammerTitle the value for grammar_table.grammer_title
     *
     * @mbg.generated Mon Apr 19 03:23:44 JST 2021
     */
    public void setGrammerTitle(String grammerTitle) {
        this.grammerTitle = grammerTitle == null ? null : grammerTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grammar_table.grammer
     *
     * @return the value of grammar_table.grammer
     *
     * @mbg.generated Mon Apr 19 03:23:44 JST 2021
     */
    public String getGrammer() {
        return grammer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grammar_table.grammer
     *
     * @param grammer the value for grammar_table.grammer
     *
     * @mbg.generated Mon Apr 19 03:23:44 JST 2021
     */
    public void setGrammer(String grammer) {
        this.grammer = grammer == null ? null : grammer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grammar_table.description
     *
     * @return the value of grammar_table.description
     *
     * @mbg.generated Mon Apr 19 03:23:44 JST 2021
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grammar_table.description
     *
     * @param description the value for grammar_table.description
     *
     * @mbg.generated Mon Apr 19 03:23:44 JST 2021
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grammar_table.creater
     *
     * @return the value of grammar_table.creater
     *
     * @mbg.generated Mon Apr 19 03:23:44 JST 2021
     */
    public String getCreater() {
        return creater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grammar_table.creater
     *
     * @param creater the value for grammar_table.creater
     *
     * @mbg.generated Mon Apr 19 03:23:44 JST 2021
     */
    public void setCreater(String creater) {
        this.creater = creater == null ? null : creater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grammar_table.create_time
     *
     * @return the value of grammar_table.create_time
     *
     * @mbg.generated Mon Apr 19 03:23:44 JST 2021
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grammar_table.create_time
     *
     * @param createTime the value for grammar_table.create_time
     *
     * @mbg.generated Mon Apr 19 03:23:44 JST 2021
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grammar_table.updater
     *
     * @return the value of grammar_table.updater
     *
     * @mbg.generated Mon Apr 19 03:23:44 JST 2021
     */
    public String getUpdater() {
        return updater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grammar_table.updater
     *
     * @param updater the value for grammar_table.updater
     *
     * @mbg.generated Mon Apr 19 03:23:44 JST 2021
     */
    public void setUpdater(String updater) {
        this.updater = updater == null ? null : updater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grammar_table.update_time
     *
     * @return the value of grammar_table.update_time
     *
     * @mbg.generated Mon Apr 19 03:23:44 JST 2021
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grammar_table.update_time
     *
     * @param updateTime the value for grammar_table.update_time
     *
     * @mbg.generated Mon Apr 19 03:23:44 JST 2021
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}