package org.innox.pojo;

public class LessonTableKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lesson_table.book_id
     *
     * @mbg.generated Wed May 12 16:37:06 JST 2021
     */
    private Long bookId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lesson_table.lesson_id
     *
     * @mbg.generated Wed May 12 16:37:06 JST 2021
     */
    private Long lessonId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lesson_table.book_id
     *
     * @return the value of lesson_table.book_id
     *
     * @mbg.generated Wed May 12 16:37:06 JST 2021
     */
    public Long getBookId() {
        return bookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lesson_table.book_id
     *
     * @param bookId the value for lesson_table.book_id
     *
     * @mbg.generated Wed May 12 16:37:06 JST 2021
     */
    public void setBookId(Long bookId) {
        this.bookId = bookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lesson_table.lesson_id
     *
     * @return the value of lesson_table.lesson_id
     *
     * @mbg.generated Wed May 12 16:37:06 JST 2021
     */
    public Long getLessonId() {
        return lessonId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lesson_table.lesson_id
     *
     * @param lessonId the value for lesson_table.lesson_id
     *
     * @mbg.generated Wed May 12 16:37:06 JST 2021
     */
    public void setLessonId(Long lessonId) {
        this.lessonId = lessonId;
    }
}