package org.innox.pojo;

import java.util.Date;

public class LessonTable extends LessonTableKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lesson_table.lesson_name_translate
     *
     * @mbg.generated Mon Apr 19 03:23:44 JST 2021
     */
    private String lessonNameTranslate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lesson_table.lesson_name_orignal
     *
     * @mbg.generated Mon Apr 19 03:23:44 JST 2021
     */
    private String lessonNameOrignal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lesson_table.description
     *
     * @mbg.generated Mon Apr 19 03:23:44 JST 2021
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lesson_table.creater
     *
     * @mbg.generated Mon Apr 19 03:23:44 JST 2021
     */
    private String creater;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lesson_table.create_time
     *
     * @mbg.generated Mon Apr 19 03:23:44 JST 2021
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lesson_table.updater
     *
     * @mbg.generated Mon Apr 19 03:23:44 JST 2021
     */
    private String updater;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lesson_table.update_time
     *
     * @mbg.generated Mon Apr 19 03:23:44 JST 2021
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lesson_table.lesson_name_translate
     *
     * @return the value of lesson_table.lesson_name_translate
     *
     * @mbg.generated Mon Apr 19 03:23:44 JST 2021
     */
    public String getLessonNameTranslate() {
        return lessonNameTranslate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lesson_table.lesson_name_translate
     *
     * @param lessonNameTranslate the value for lesson_table.lesson_name_translate
     *
     * @mbg.generated Mon Apr 19 03:23:44 JST 2021
     */
    public void setLessonNameTranslate(String lessonNameTranslate) {
        this.lessonNameTranslate = lessonNameTranslate == null ? null : lessonNameTranslate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lesson_table.lesson_name_orignal
     *
     * @return the value of lesson_table.lesson_name_orignal
     *
     * @mbg.generated Mon Apr 19 03:23:44 JST 2021
     */
    public String getLessonNameOrignal() {
        return lessonNameOrignal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lesson_table.lesson_name_orignal
     *
     * @param lessonNameOrignal the value for lesson_table.lesson_name_orignal
     *
     * @mbg.generated Mon Apr 19 03:23:44 JST 2021
     */
    public void setLessonNameOrignal(String lessonNameOrignal) {
        this.lessonNameOrignal = lessonNameOrignal == null ? null : lessonNameOrignal.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lesson_table.description
     *
     * @return the value of lesson_table.description
     *
     * @mbg.generated Mon Apr 19 03:23:44 JST 2021
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lesson_table.description
     *
     * @param description the value for lesson_table.description
     *
     * @mbg.generated Mon Apr 19 03:23:44 JST 2021
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lesson_table.creater
     *
     * @return the value of lesson_table.creater
     *
     * @mbg.generated Mon Apr 19 03:23:44 JST 2021
     */
    public String getCreater() {
        return creater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lesson_table.creater
     *
     * @param creater the value for lesson_table.creater
     *
     * @mbg.generated Mon Apr 19 03:23:44 JST 2021
     */
    public void setCreater(String creater) {
        this.creater = creater == null ? null : creater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lesson_table.create_time
     *
     * @return the value of lesson_table.create_time
     *
     * @mbg.generated Mon Apr 19 03:23:44 JST 2021
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lesson_table.create_time
     *
     * @param createTime the value for lesson_table.create_time
     *
     * @mbg.generated Mon Apr 19 03:23:44 JST 2021
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lesson_table.updater
     *
     * @return the value of lesson_table.updater
     *
     * @mbg.generated Mon Apr 19 03:23:44 JST 2021
     */
    public String getUpdater() {
        return updater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lesson_table.updater
     *
     * @param updater the value for lesson_table.updater
     *
     * @mbg.generated Mon Apr 19 03:23:44 JST 2021
     */
    public void setUpdater(String updater) {
        this.updater = updater == null ? null : updater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lesson_table.update_time
     *
     * @return the value of lesson_table.update_time
     *
     * @mbg.generated Mon Apr 19 03:23:44 JST 2021
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lesson_table.update_time
     *
     * @param updateTime the value for lesson_table.update_time
     *
     * @mbg.generated Mon Apr 19 03:23:44 JST 2021
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}