package org.innox.pojo;

import java.util.Date;

public class PhraseTable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phrase_table.phrase_id
     *
     * @mbg.generated Mon Apr 26 20:05:47 JST 2021
     */
    private Long phraseId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phrase_table.phrase_type
     *
     * @mbg.generated Mon Apr 26 20:05:47 JST 2021
     */
    private String phraseType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phrase_table.phrase_name_translate
     *
     * @mbg.generated Mon Apr 26 20:05:47 JST 2021
     */
    private String phraseNameTranslate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phrase_table.phrase_name_orignal
     *
     * @mbg.generated Mon Apr 26 20:05:47 JST 2021
     */
    private String phraseNameOrignal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phrase_table.description
     *
     * @mbg.generated Mon Apr 26 20:05:47 JST 2021
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phrase_table.creater
     *
     * @mbg.generated Mon Apr 26 20:05:47 JST 2021
     */
    private String creater;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phrase_table.create_time
     *
     * @mbg.generated Mon Apr 26 20:05:47 JST 2021
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phrase_table.updater
     *
     * @mbg.generated Mon Apr 26 20:05:47 JST 2021
     */
    private String updater;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phrase_table.update_time
     *
     * @mbg.generated Mon Apr 26 20:05:47 JST 2021
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phrase_table.phrase_id
     *
     * @return the value of phrase_table.phrase_id
     *
     * @mbg.generated Mon Apr 26 20:05:47 JST 2021
     */
    public Long getPhraseId() {
        return phraseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phrase_table.phrase_id
     *
     * @param phraseId the value for phrase_table.phrase_id
     *
     * @mbg.generated Mon Apr 26 20:05:47 JST 2021
     */
    public void setPhraseId(Long phraseId) {
        this.phraseId = phraseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phrase_table.phrase_type
     *
     * @return the value of phrase_table.phrase_type
     *
     * @mbg.generated Mon Apr 26 20:05:47 JST 2021
     */
    public String getPhraseType() {
        return phraseType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phrase_table.phrase_type
     *
     * @param phraseType the value for phrase_table.phrase_type
     *
     * @mbg.generated Mon Apr 26 20:05:47 JST 2021
     */
    public void setPhraseType(String phraseType) {
        this.phraseType = phraseType == null ? null : phraseType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phrase_table.phrase_name_translate
     *
     * @return the value of phrase_table.phrase_name_translate
     *
     * @mbg.generated Mon Apr 26 20:05:47 JST 2021
     */
    public String getPhraseNameTranslate() {
        return phraseNameTranslate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phrase_table.phrase_name_translate
     *
     * @param phraseNameTranslate the value for phrase_table.phrase_name_translate
     *
     * @mbg.generated Mon Apr 26 20:05:47 JST 2021
     */
    public void setPhraseNameTranslate(String phraseNameTranslate) {
        this.phraseNameTranslate = phraseNameTranslate == null ? null : phraseNameTranslate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phrase_table.phrase_name_orignal
     *
     * @return the value of phrase_table.phrase_name_orignal
     *
     * @mbg.generated Mon Apr 26 20:05:47 JST 2021
     */
    public String getPhraseNameOrignal() {
        return phraseNameOrignal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phrase_table.phrase_name_orignal
     *
     * @param phraseNameOrignal the value for phrase_table.phrase_name_orignal
     *
     * @mbg.generated Mon Apr 26 20:05:47 JST 2021
     */
    public void setPhraseNameOrignal(String phraseNameOrignal) {
        this.phraseNameOrignal = phraseNameOrignal == null ? null : phraseNameOrignal.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phrase_table.description
     *
     * @return the value of phrase_table.description
     *
     * @mbg.generated Mon Apr 26 20:05:47 JST 2021
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phrase_table.description
     *
     * @param description the value for phrase_table.description
     *
     * @mbg.generated Mon Apr 26 20:05:47 JST 2021
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phrase_table.creater
     *
     * @return the value of phrase_table.creater
     *
     * @mbg.generated Mon Apr 26 20:05:47 JST 2021
     */
    public String getCreater() {
        return creater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phrase_table.creater
     *
     * @param creater the value for phrase_table.creater
     *
     * @mbg.generated Mon Apr 26 20:05:47 JST 2021
     */
    public void setCreater(String creater) {
        this.creater = creater == null ? null : creater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phrase_table.create_time
     *
     * @return the value of phrase_table.create_time
     *
     * @mbg.generated Mon Apr 26 20:05:47 JST 2021
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phrase_table.create_time
     *
     * @param createTime the value for phrase_table.create_time
     *
     * @mbg.generated Mon Apr 26 20:05:47 JST 2021
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phrase_table.updater
     *
     * @return the value of phrase_table.updater
     *
     * @mbg.generated Mon Apr 26 20:05:47 JST 2021
     */
    public String getUpdater() {
        return updater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phrase_table.updater
     *
     * @param updater the value for phrase_table.updater
     *
     * @mbg.generated Mon Apr 26 20:05:47 JST 2021
     */
    public void setUpdater(String updater) {
        this.updater = updater == null ? null : updater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phrase_table.update_time
     *
     * @return the value of phrase_table.update_time
     *
     * @mbg.generated Mon Apr 26 20:05:47 JST 2021
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phrase_table.update_time
     *
     * @param updateTime the value for phrase_table.update_time
     *
     * @mbg.generated Mon Apr 26 20:05:47 JST 2021
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}