package org.innox.pojo;

public class SentenceGrammerTableKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sentence_grammer_table.grammer_id
     *
     * @mbg.generated Wed May 12 16:37:06 JST 2021
     */
    private Long grammerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sentence_grammer_table.sentence_seq
     *
     * @mbg.generated Wed May 12 16:37:06 JST 2021
     */
    private Long sentenceSeq;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sentence_grammer_table.grammer_id
     *
     * @return the value of sentence_grammer_table.grammer_id
     *
     * @mbg.generated Wed May 12 16:37:06 JST 2021
     */
    public Long getGrammerId() {
        return grammerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sentence_grammer_table.grammer_id
     *
     * @param grammerId the value for sentence_grammer_table.grammer_id
     *
     * @mbg.generated Wed May 12 16:37:06 JST 2021
     */
    public void setGrammerId(Long grammerId) {
        this.grammerId = grammerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sentence_grammer_table.sentence_seq
     *
     * @return the value of sentence_grammer_table.sentence_seq
     *
     * @mbg.generated Wed May 12 16:37:06 JST 2021
     */
    public Long getSentenceSeq() {
        return sentenceSeq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sentence_grammer_table.sentence_seq
     *
     * @param sentenceSeq the value for sentence_grammer_table.sentence_seq
     *
     * @mbg.generated Wed May 12 16:37:06 JST 2021
     */
    public void setSentenceSeq(Long sentenceSeq) {
        this.sentenceSeq = sentenceSeq;
    }
}