package org.innox.pojo;

public class SentencePhraseTableKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sentence_phrase_table.phrase_id
     *
     * @mbg.generated Wed May 12 16:37:06 JST 2021
     */
    private Long phraseId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sentence_phrase_table.sentence_seq
     *
     * @mbg.generated Wed May 12 16:37:06 JST 2021
     */
    private Long sentenceSeq;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sentence_phrase_table.phrase_id
     *
     * @return the value of sentence_phrase_table.phrase_id
     *
     * @mbg.generated Wed May 12 16:37:06 JST 2021
     */
    public Long getPhraseId() {
        return phraseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sentence_phrase_table.phrase_id
     *
     * @param phraseId the value for sentence_phrase_table.phrase_id
     *
     * @mbg.generated Wed May 12 16:37:06 JST 2021
     */
    public void setPhraseId(Long phraseId) {
        this.phraseId = phraseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sentence_phrase_table.sentence_seq
     *
     * @return the value of sentence_phrase_table.sentence_seq
     *
     * @mbg.generated Wed May 12 16:37:06 JST 2021
     */
    public Long getSentenceSeq() {
        return sentenceSeq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sentence_phrase_table.sentence_seq
     *
     * @param sentenceSeq the value for sentence_phrase_table.sentence_seq
     *
     * @mbg.generated Wed May 12 16:37:06 JST 2021
     */
    public void setSentenceSeq(Long sentenceSeq) {
        this.sentenceSeq = sentenceSeq;
    }
}