package org.innox.pojo;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class SentenceTableExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sentence_table
     *
     * @mbg.generated Wed May 12 16:37:06 JST 2021
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sentence_table
     *
     * @mbg.generated Wed May 12 16:37:06 JST 2021
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sentence_table
     *
     * @mbg.generated Wed May 12 16:37:06 JST 2021
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sentence_table
     *
     * @mbg.generated Wed May 12 16:37:06 JST 2021
     */
    public SentenceTableExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sentence_table
     *
     * @mbg.generated Wed May 12 16:37:06 JST 2021
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sentence_table
     *
     * @mbg.generated Wed May 12 16:37:06 JST 2021
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sentence_table
     *
     * @mbg.generated Wed May 12 16:37:06 JST 2021
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sentence_table
     *
     * @mbg.generated Wed May 12 16:37:06 JST 2021
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sentence_table
     *
     * @mbg.generated Wed May 12 16:37:06 JST 2021
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sentence_table
     *
     * @mbg.generated Wed May 12 16:37:06 JST 2021
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sentence_table
     *
     * @mbg.generated Wed May 12 16:37:06 JST 2021
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sentence_table
     *
     * @mbg.generated Wed May 12 16:37:06 JST 2021
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sentence_table
     *
     * @mbg.generated Wed May 12 16:37:06 JST 2021
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sentence_table
     *
     * @mbg.generated Wed May 12 16:37:06 JST 2021
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sentence_table
     *
     * @mbg.generated Wed May 12 16:37:06 JST 2021
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andSentenceSeqIsNull() {
            addCriterion("sentence_seq is null");
            return (Criteria) this;
        }

        public Criteria andSentenceSeqIsNotNull() {
            addCriterion("sentence_seq is not null");
            return (Criteria) this;
        }

        public Criteria andSentenceSeqEqualTo(Long value) {
            addCriterion("sentence_seq =", value, "sentenceSeq");
            return (Criteria) this;
        }

        public Criteria andSentenceSeqNotEqualTo(Long value) {
            addCriterion("sentence_seq <>", value, "sentenceSeq");
            return (Criteria) this;
        }

        public Criteria andSentenceSeqGreaterThan(Long value) {
            addCriterion("sentence_seq >", value, "sentenceSeq");
            return (Criteria) this;
        }

        public Criteria andSentenceSeqGreaterThanOrEqualTo(Long value) {
            addCriterion("sentence_seq >=", value, "sentenceSeq");
            return (Criteria) this;
        }

        public Criteria andSentenceSeqLessThan(Long value) {
            addCriterion("sentence_seq <", value, "sentenceSeq");
            return (Criteria) this;
        }

        public Criteria andSentenceSeqLessThanOrEqualTo(Long value) {
            addCriterion("sentence_seq <=", value, "sentenceSeq");
            return (Criteria) this;
        }

        public Criteria andSentenceSeqIn(List<Long> values) {
            addCriterion("sentence_seq in", values, "sentenceSeq");
            return (Criteria) this;
        }

        public Criteria andSentenceSeqNotIn(List<Long> values) {
            addCriterion("sentence_seq not in", values, "sentenceSeq");
            return (Criteria) this;
        }

        public Criteria andSentenceSeqBetween(Long value1, Long value2) {
            addCriterion("sentence_seq between", value1, value2, "sentenceSeq");
            return (Criteria) this;
        }

        public Criteria andSentenceSeqNotBetween(Long value1, Long value2) {
            addCriterion("sentence_seq not between", value1, value2, "sentenceSeq");
            return (Criteria) this;
        }

        public Criteria andBookIdIsNull() {
            addCriterion("book_id is null");
            return (Criteria) this;
        }

        public Criteria andBookIdIsNotNull() {
            addCriterion("book_id is not null");
            return (Criteria) this;
        }

        public Criteria andBookIdEqualTo(Long value) {
            addCriterion("book_id =", value, "bookId");
            return (Criteria) this;
        }

        public Criteria andBookIdNotEqualTo(Long value) {
            addCriterion("book_id <>", value, "bookId");
            return (Criteria) this;
        }

        public Criteria andBookIdGreaterThan(Long value) {
            addCriterion("book_id >", value, "bookId");
            return (Criteria) this;
        }

        public Criteria andBookIdGreaterThanOrEqualTo(Long value) {
            addCriterion("book_id >=", value, "bookId");
            return (Criteria) this;
        }

        public Criteria andBookIdLessThan(Long value) {
            addCriterion("book_id <", value, "bookId");
            return (Criteria) this;
        }

        public Criteria andBookIdLessThanOrEqualTo(Long value) {
            addCriterion("book_id <=", value, "bookId");
            return (Criteria) this;
        }

        public Criteria andBookIdIn(List<Long> values) {
            addCriterion("book_id in", values, "bookId");
            return (Criteria) this;
        }

        public Criteria andBookIdNotIn(List<Long> values) {
            addCriterion("book_id not in", values, "bookId");
            return (Criteria) this;
        }

        public Criteria andBookIdBetween(Long value1, Long value2) {
            addCriterion("book_id between", value1, value2, "bookId");
            return (Criteria) this;
        }

        public Criteria andBookIdNotBetween(Long value1, Long value2) {
            addCriterion("book_id not between", value1, value2, "bookId");
            return (Criteria) this;
        }

        public Criteria andLessonIdIsNull() {
            addCriterion("lesson_id is null");
            return (Criteria) this;
        }

        public Criteria andLessonIdIsNotNull() {
            addCriterion("lesson_id is not null");
            return (Criteria) this;
        }

        public Criteria andLessonIdEqualTo(Long value) {
            addCriterion("lesson_id =", value, "lessonId");
            return (Criteria) this;
        }

        public Criteria andLessonIdNotEqualTo(Long value) {
            addCriterion("lesson_id <>", value, "lessonId");
            return (Criteria) this;
        }

        public Criteria andLessonIdGreaterThan(Long value) {
            addCriterion("lesson_id >", value, "lessonId");
            return (Criteria) this;
        }

        public Criteria andLessonIdGreaterThanOrEqualTo(Long value) {
            addCriterion("lesson_id >=", value, "lessonId");
            return (Criteria) this;
        }

        public Criteria andLessonIdLessThan(Long value) {
            addCriterion("lesson_id <", value, "lessonId");
            return (Criteria) this;
        }

        public Criteria andLessonIdLessThanOrEqualTo(Long value) {
            addCriterion("lesson_id <=", value, "lessonId");
            return (Criteria) this;
        }

        public Criteria andLessonIdIn(List<Long> values) {
            addCriterion("lesson_id in", values, "lessonId");
            return (Criteria) this;
        }

        public Criteria andLessonIdNotIn(List<Long> values) {
            addCriterion("lesson_id not in", values, "lessonId");
            return (Criteria) this;
        }

        public Criteria andLessonIdBetween(Long value1, Long value2) {
            addCriterion("lesson_id between", value1, value2, "lessonId");
            return (Criteria) this;
        }

        public Criteria andLessonIdNotBetween(Long value1, Long value2) {
            addCriterion("lesson_id not between", value1, value2, "lessonId");
            return (Criteria) this;
        }

        public Criteria andLineNoIsNull() {
            addCriterion("line_no is null");
            return (Criteria) this;
        }

        public Criteria andLineNoIsNotNull() {
            addCriterion("line_no is not null");
            return (Criteria) this;
        }

        public Criteria andLineNoEqualTo(Long value) {
            addCriterion("line_no =", value, "lineNo");
            return (Criteria) this;
        }

        public Criteria andLineNoNotEqualTo(Long value) {
            addCriterion("line_no <>", value, "lineNo");
            return (Criteria) this;
        }

        public Criteria andLineNoGreaterThan(Long value) {
            addCriterion("line_no >", value, "lineNo");
            return (Criteria) this;
        }

        public Criteria andLineNoGreaterThanOrEqualTo(Long value) {
            addCriterion("line_no >=", value, "lineNo");
            return (Criteria) this;
        }

        public Criteria andLineNoLessThan(Long value) {
            addCriterion("line_no <", value, "lineNo");
            return (Criteria) this;
        }

        public Criteria andLineNoLessThanOrEqualTo(Long value) {
            addCriterion("line_no <=", value, "lineNo");
            return (Criteria) this;
        }

        public Criteria andLineNoIn(List<Long> values) {
            addCriterion("line_no in", values, "lineNo");
            return (Criteria) this;
        }

        public Criteria andLineNoNotIn(List<Long> values) {
            addCriterion("line_no not in", values, "lineNo");
            return (Criteria) this;
        }

        public Criteria andLineNoBetween(Long value1, Long value2) {
            addCriterion("line_no between", value1, value2, "lineNo");
            return (Criteria) this;
        }

        public Criteria andLineNoNotBetween(Long value1, Long value2) {
            addCriterion("line_no not between", value1, value2, "lineNo");
            return (Criteria) this;
        }

        public Criteria andSentenceTypeIsNull() {
            addCriterion("sentence_type is null");
            return (Criteria) this;
        }

        public Criteria andSentenceTypeIsNotNull() {
            addCriterion("sentence_type is not null");
            return (Criteria) this;
        }

        public Criteria andSentenceTypeEqualTo(String value) {
            addCriterion("sentence_type =", value, "sentenceType");
            return (Criteria) this;
        }

        public Criteria andSentenceTypeNotEqualTo(String value) {
            addCriterion("sentence_type <>", value, "sentenceType");
            return (Criteria) this;
        }

        public Criteria andSentenceTypeGreaterThan(String value) {
            addCriterion("sentence_type >", value, "sentenceType");
            return (Criteria) this;
        }

        public Criteria andSentenceTypeGreaterThanOrEqualTo(String value) {
            addCriterion("sentence_type >=", value, "sentenceType");
            return (Criteria) this;
        }

        public Criteria andSentenceTypeLessThan(String value) {
            addCriterion("sentence_type <", value, "sentenceType");
            return (Criteria) this;
        }

        public Criteria andSentenceTypeLessThanOrEqualTo(String value) {
            addCriterion("sentence_type <=", value, "sentenceType");
            return (Criteria) this;
        }

        public Criteria andSentenceTypeLike(String value) {
            addCriterion("sentence_type like", value, "sentenceType");
            return (Criteria) this;
        }

        public Criteria andSentenceTypeNotLike(String value) {
            addCriterion("sentence_type not like", value, "sentenceType");
            return (Criteria) this;
        }

        public Criteria andSentenceTypeIn(List<String> values) {
            addCriterion("sentence_type in", values, "sentenceType");
            return (Criteria) this;
        }

        public Criteria andSentenceTypeNotIn(List<String> values) {
            addCriterion("sentence_type not in", values, "sentenceType");
            return (Criteria) this;
        }

        public Criteria andSentenceTypeBetween(String value1, String value2) {
            addCriterion("sentence_type between", value1, value2, "sentenceType");
            return (Criteria) this;
        }

        public Criteria andSentenceTypeNotBetween(String value1, String value2) {
            addCriterion("sentence_type not between", value1, value2, "sentenceType");
            return (Criteria) this;
        }

        public Criteria andSentenceNameTranslateIsNull() {
            addCriterion("sentence_name_translate is null");
            return (Criteria) this;
        }

        public Criteria andSentenceNameTranslateIsNotNull() {
            addCriterion("sentence_name_translate is not null");
            return (Criteria) this;
        }

        public Criteria andSentenceNameTranslateEqualTo(String value) {
            addCriterion("sentence_name_translate =", value, "sentenceNameTranslate");
            return (Criteria) this;
        }

        public Criteria andSentenceNameTranslateNotEqualTo(String value) {
            addCriterion("sentence_name_translate <>", value, "sentenceNameTranslate");
            return (Criteria) this;
        }

        public Criteria andSentenceNameTranslateGreaterThan(String value) {
            addCriterion("sentence_name_translate >", value, "sentenceNameTranslate");
            return (Criteria) this;
        }

        public Criteria andSentenceNameTranslateGreaterThanOrEqualTo(String value) {
            addCriterion("sentence_name_translate >=", value, "sentenceNameTranslate");
            return (Criteria) this;
        }

        public Criteria andSentenceNameTranslateLessThan(String value) {
            addCriterion("sentence_name_translate <", value, "sentenceNameTranslate");
            return (Criteria) this;
        }

        public Criteria andSentenceNameTranslateLessThanOrEqualTo(String value) {
            addCriterion("sentence_name_translate <=", value, "sentenceNameTranslate");
            return (Criteria) this;
        }

        public Criteria andSentenceNameTranslateLike(String value) {
            addCriterion("sentence_name_translate like", value, "sentenceNameTranslate");
            return (Criteria) this;
        }

        public Criteria andSentenceNameTranslateNotLike(String value) {
            addCriterion("sentence_name_translate not like", value, "sentenceNameTranslate");
            return (Criteria) this;
        }

        public Criteria andSentenceNameTranslateIn(List<String> values) {
            addCriterion("sentence_name_translate in", values, "sentenceNameTranslate");
            return (Criteria) this;
        }

        public Criteria andSentenceNameTranslateNotIn(List<String> values) {
            addCriterion("sentence_name_translate not in", values, "sentenceNameTranslate");
            return (Criteria) this;
        }

        public Criteria andSentenceNameTranslateBetween(String value1, String value2) {
            addCriterion("sentence_name_translate between", value1, value2, "sentenceNameTranslate");
            return (Criteria) this;
        }

        public Criteria andSentenceNameTranslateNotBetween(String value1, String value2) {
            addCriterion("sentence_name_translate not between", value1, value2, "sentenceNameTranslate");
            return (Criteria) this;
        }

        public Criteria andSentenceNameOrignalIsNull() {
            addCriterion("sentence_name_orignal is null");
            return (Criteria) this;
        }

        public Criteria andSentenceNameOrignalIsNotNull() {
            addCriterion("sentence_name_orignal is not null");
            return (Criteria) this;
        }

        public Criteria andSentenceNameOrignalEqualTo(String value) {
            addCriterion("sentence_name_orignal =", value, "sentenceNameOrignal");
            return (Criteria) this;
        }

        public Criteria andSentenceNameOrignalNotEqualTo(String value) {
            addCriterion("sentence_name_orignal <>", value, "sentenceNameOrignal");
            return (Criteria) this;
        }

        public Criteria andSentenceNameOrignalGreaterThan(String value) {
            addCriterion("sentence_name_orignal >", value, "sentenceNameOrignal");
            return (Criteria) this;
        }

        public Criteria andSentenceNameOrignalGreaterThanOrEqualTo(String value) {
            addCriterion("sentence_name_orignal >=", value, "sentenceNameOrignal");
            return (Criteria) this;
        }

        public Criteria andSentenceNameOrignalLessThan(String value) {
            addCriterion("sentence_name_orignal <", value, "sentenceNameOrignal");
            return (Criteria) this;
        }

        public Criteria andSentenceNameOrignalLessThanOrEqualTo(String value) {
            addCriterion("sentence_name_orignal <=", value, "sentenceNameOrignal");
            return (Criteria) this;
        }

        public Criteria andSentenceNameOrignalLike(String value) {
            addCriterion("sentence_name_orignal like", value, "sentenceNameOrignal");
            return (Criteria) this;
        }

        public Criteria andSentenceNameOrignalNotLike(String value) {
            addCriterion("sentence_name_orignal not like", value, "sentenceNameOrignal");
            return (Criteria) this;
        }

        public Criteria andSentenceNameOrignalIn(List<String> values) {
            addCriterion("sentence_name_orignal in", values, "sentenceNameOrignal");
            return (Criteria) this;
        }

        public Criteria andSentenceNameOrignalNotIn(List<String> values) {
            addCriterion("sentence_name_orignal not in", values, "sentenceNameOrignal");
            return (Criteria) this;
        }

        public Criteria andSentenceNameOrignalBetween(String value1, String value2) {
            addCriterion("sentence_name_orignal between", value1, value2, "sentenceNameOrignal");
            return (Criteria) this;
        }

        public Criteria andSentenceNameOrignalNotBetween(String value1, String value2) {
            addCriterion("sentence_name_orignal not between", value1, value2, "sentenceNameOrignal");
            return (Criteria) this;
        }

        public Criteria andDescriptionIsNull() {
            addCriterion("description is null");
            return (Criteria) this;
        }

        public Criteria andDescriptionIsNotNull() {
            addCriterion("description is not null");
            return (Criteria) this;
        }

        public Criteria andDescriptionEqualTo(String value) {
            addCriterion("description =", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotEqualTo(String value) {
            addCriterion("description <>", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionGreaterThan(String value) {
            addCriterion("description >", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionGreaterThanOrEqualTo(String value) {
            addCriterion("description >=", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLessThan(String value) {
            addCriterion("description <", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLessThanOrEqualTo(String value) {
            addCriterion("description <=", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLike(String value) {
            addCriterion("description like", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotLike(String value) {
            addCriterion("description not like", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionIn(List<String> values) {
            addCriterion("description in", values, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotIn(List<String> values) {
            addCriterion("description not in", values, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionBetween(String value1, String value2) {
            addCriterion("description between", value1, value2, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotBetween(String value1, String value2) {
            addCriterion("description not between", value1, value2, "description");
            return (Criteria) this;
        }

        public Criteria andCreaterIsNull() {
            addCriterion("creater is null");
            return (Criteria) this;
        }

        public Criteria andCreaterIsNotNull() {
            addCriterion("creater is not null");
            return (Criteria) this;
        }

        public Criteria andCreaterEqualTo(String value) {
            addCriterion("creater =", value, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterNotEqualTo(String value) {
            addCriterion("creater <>", value, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterGreaterThan(String value) {
            addCriterion("creater >", value, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterGreaterThanOrEqualTo(String value) {
            addCriterion("creater >=", value, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterLessThan(String value) {
            addCriterion("creater <", value, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterLessThanOrEqualTo(String value) {
            addCriterion("creater <=", value, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterLike(String value) {
            addCriterion("creater like", value, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterNotLike(String value) {
            addCriterion("creater not like", value, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterIn(List<String> values) {
            addCriterion("creater in", values, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterNotIn(List<String> values) {
            addCriterion("creater not in", values, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterBetween(String value1, String value2) {
            addCriterion("creater between", value1, value2, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterNotBetween(String value1, String value2) {
            addCriterion("creater not between", value1, value2, "creater");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andUpdaterIsNull() {
            addCriterion("updater is null");
            return (Criteria) this;
        }

        public Criteria andUpdaterIsNotNull() {
            addCriterion("updater is not null");
            return (Criteria) this;
        }

        public Criteria andUpdaterEqualTo(String value) {
            addCriterion("updater =", value, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterNotEqualTo(String value) {
            addCriterion("updater <>", value, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterGreaterThan(String value) {
            addCriterion("updater >", value, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterGreaterThanOrEqualTo(String value) {
            addCriterion("updater >=", value, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterLessThan(String value) {
            addCriterion("updater <", value, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterLessThanOrEqualTo(String value) {
            addCriterion("updater <=", value, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterLike(String value) {
            addCriterion("updater like", value, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterNotLike(String value) {
            addCriterion("updater not like", value, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterIn(List<String> values) {
            addCriterion("updater in", values, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterNotIn(List<String> values) {
            addCriterion("updater not in", values, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterBetween(String value1, String value2) {
            addCriterion("updater between", value1, value2, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterNotBetween(String value1, String value2) {
            addCriterion("updater not between", value1, value2, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sentence_table
     *
     * @mbg.generated do_not_delete_during_merge Wed May 12 16:37:06 JST 2021
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sentence_table
     *
     * @mbg.generated Wed May 12 16:37:06 JST 2021
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}