package org.innox.pojo;

import java.util.Date;

public class SentenceWordTable extends SentenceWordTableKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sentence_word_table.creater
     *
     * @mbg.generated Mon Apr 26 20:05:47 JST 2021
     */
    private String creater;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sentence_word_table.create_time
     *
     * @mbg.generated Mon Apr 26 20:05:47 JST 2021
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sentence_word_table.updater
     *
     * @mbg.generated Mon Apr 26 20:05:47 JST 2021
     */
    private String updater;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sentence_word_table.update_time
     *
     * @mbg.generated Mon Apr 26 20:05:47 JST 2021
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sentence_word_table.creater
     *
     * @return the value of sentence_word_table.creater
     *
     * @mbg.generated Mon Apr 26 20:05:47 JST 2021
     */
    public String getCreater() {
        return creater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sentence_word_table.creater
     *
     * @param creater the value for sentence_word_table.creater
     *
     * @mbg.generated Mon Apr 26 20:05:47 JST 2021
     */
    public void setCreater(String creater) {
        this.creater = creater == null ? null : creater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sentence_word_table.create_time
     *
     * @return the value of sentence_word_table.create_time
     *
     * @mbg.generated Mon Apr 26 20:05:47 JST 2021
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sentence_word_table.create_time
     *
     * @param createTime the value for sentence_word_table.create_time
     *
     * @mbg.generated Mon Apr 26 20:05:47 JST 2021
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sentence_word_table.updater
     *
     * @return the value of sentence_word_table.updater
     *
     * @mbg.generated Mon Apr 26 20:05:47 JST 2021
     */
    public String getUpdater() {
        return updater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sentence_word_table.updater
     *
     * @param updater the value for sentence_word_table.updater
     *
     * @mbg.generated Mon Apr 26 20:05:47 JST 2021
     */
    public void setUpdater(String updater) {
        this.updater = updater == null ? null : updater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sentence_word_table.update_time
     *
     * @return the value of sentence_word_table.update_time
     *
     * @mbg.generated Mon Apr 26 20:05:47 JST 2021
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sentence_word_table.update_time
     *
     * @param updateTime the value for sentence_word_table.update_time
     *
     * @mbg.generated Mon Apr 26 20:05:47 JST 2021
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}