package org.innox.pojo;

public class SentenceGrammerTableKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sentence_grammer_table.grammar_id
     *
     * @mbg.generated Mon Apr 19 03:23:44 JST 2021
     */
    private Long grammarId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sentence_grammer_table.sentence_seq
     *
     * @mbg.generated Mon Apr 19 03:23:44 JST 2021
     */
    private Long sentenceSeq;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sentence_grammer_table.grammar_id
     *
     * @return the value of sentence_grammer_table.grammar_id
     *
     * @mbg.generated Mon Apr 19 03:23:44 JST 2021
     */
    public Long getGrammarId() {
        return grammarId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sentence_grammer_table.grammar_id
     *
     * @param grammarId the value for sentence_grammer_table.grammar_id
     *
     * @mbg.generated Mon Apr 19 03:23:44 JST 2021
     */
    public void setGrammarId(Long grammarId) {
        this.grammarId = grammarId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sentence_grammer_table.sentence_seq
     *
     * @return the value of sentence_grammer_table.sentence_seq
     *
     * @mbg.generated Mon Apr 19 03:23:44 JST 2021
     */
    public Long getSentenceSeq() {
        return sentenceSeq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sentence_grammer_table.sentence_seq
     *
     * @param sentenceSeq the value for sentence_grammer_table.sentence_seq
     *
     * @mbg.generated Mon Apr 19 03:23:44 JST 2021
     */
    public void setSentenceSeq(Long sentenceSeq) {
        this.sentenceSeq = sentenceSeq;
    }
}