package org.innox.pojo;

import java.util.Date;

public class UserPracticeHistory {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_practice_history.history_id
     *
     * @mbg.generated Wed May 12 16:37:06 JST 2021
     */
    private Long historyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_practice_history.user_id
     *
     * @mbg.generated Wed May 12 16:37:06 JST 2021
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_practice_history.sentence_seq
     *
     * @mbg.generated Wed May 12 16:37:06 JST 2021
     */
    private Long sentenceSeq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_practice_history.mistake_count
     *
     * @mbg.generated Wed May 12 16:37:06 JST 2021
     */
    private Long mistakeCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_practice_history.creater
     *
     * @mbg.generated Wed May 12 16:37:06 JST 2021
     */
    private String creater;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_practice_history.create_time
     *
     * @mbg.generated Wed May 12 16:37:06 JST 2021
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_practice_history.updater
     *
     * @mbg.generated Wed May 12 16:37:06 JST 2021
     */
    private String updater;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_practice_history.update_time
     *
     * @mbg.generated Wed May 12 16:37:06 JST 2021
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_practice_history.history_id
     *
     * @return the value of user_practice_history.history_id
     *
     * @mbg.generated Wed May 12 16:37:06 JST 2021
     */
    public Long getHistoryId() {
        return historyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_practice_history.history_id
     *
     * @param historyId the value for user_practice_history.history_id
     *
     * @mbg.generated Wed May 12 16:37:06 JST 2021
     */
    public void setHistoryId(Long historyId) {
        this.historyId = historyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_practice_history.user_id
     *
     * @return the value of user_practice_history.user_id
     *
     * @mbg.generated Wed May 12 16:37:06 JST 2021
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_practice_history.user_id
     *
     * @param userId the value for user_practice_history.user_id
     *
     * @mbg.generated Wed May 12 16:37:06 JST 2021
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_practice_history.sentence_seq
     *
     * @return the value of user_practice_history.sentence_seq
     *
     * @mbg.generated Wed May 12 16:37:06 JST 2021
     */
    public Long getSentenceSeq() {
        return sentenceSeq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_practice_history.sentence_seq
     *
     * @param sentenceSeq the value for user_practice_history.sentence_seq
     *
     * @mbg.generated Wed May 12 16:37:06 JST 2021
     */
    public void setSentenceSeq(Long sentenceSeq) {
        this.sentenceSeq = sentenceSeq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_practice_history.mistake_count
     *
     * @return the value of user_practice_history.mistake_count
     *
     * @mbg.generated Wed May 12 16:37:06 JST 2021
     */
    public Long getMistakeCount() {
        return mistakeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_practice_history.mistake_count
     *
     * @param mistakeCount the value for user_practice_history.mistake_count
     *
     * @mbg.generated Wed May 12 16:37:06 JST 2021
     */
    public void setMistakeCount(Long mistakeCount) {
        this.mistakeCount = mistakeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_practice_history.creater
     *
     * @return the value of user_practice_history.creater
     *
     * @mbg.generated Wed May 12 16:37:06 JST 2021
     */
    public String getCreater() {
        return creater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_practice_history.creater
     *
     * @param creater the value for user_practice_history.creater
     *
     * @mbg.generated Wed May 12 16:37:06 JST 2021
     */
    public void setCreater(String creater) {
        this.creater = creater == null ? null : creater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_practice_history.create_time
     *
     * @return the value of user_practice_history.create_time
     *
     * @mbg.generated Wed May 12 16:37:06 JST 2021
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_practice_history.create_time
     *
     * @param createTime the value for user_practice_history.create_time
     *
     * @mbg.generated Wed May 12 16:37:06 JST 2021
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_practice_history.updater
     *
     * @return the value of user_practice_history.updater
     *
     * @mbg.generated Wed May 12 16:37:06 JST 2021
     */
    public String getUpdater() {
        return updater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_practice_history.updater
     *
     * @param updater the value for user_practice_history.updater
     *
     * @mbg.generated Wed May 12 16:37:06 JST 2021
     */
    public void setUpdater(String updater) {
        this.updater = updater == null ? null : updater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_practice_history.update_time
     *
     * @return the value of user_practice_history.update_time
     *
     * @mbg.generated Wed May 12 16:37:06 JST 2021
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_practice_history.update_time
     *
     * @param updateTime the value for user_practice_history.update_time
     *
     * @mbg.generated Wed May 12 16:37:06 JST 2021
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}