package org.innox.pojo;

import java.util.Date;

public class UserInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.user_id
     *
     * @mbg.generated Mon Apr 26 20:05:47 JST 2021
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.user_name
     *
     * @mbg.generated Mon Apr 26 20:05:47 JST 2021
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.password
     *
     * @mbg.generated Mon Apr 26 20:05:47 JST 2021
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.authority
     *
     * @mbg.generated Mon Apr 26 20:05:47 JST 2021
     */
    private Integer authority;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.password_history
     *
     * @mbg.generated Mon Apr 26 20:05:47 JST 2021
     */
    private String passwordHistory;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.description
     *
     * @mbg.generated Mon Apr 26 20:05:47 JST 2021
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.creater
     *
     * @mbg.generated Mon Apr 26 20:05:47 JST 2021
     */
    private String creater;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.create_time
     *
     * @mbg.generated Mon Apr 26 20:05:47 JST 2021
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.updater
     *
     * @mbg.generated Mon Apr 26 20:05:47 JST 2021
     */
    private String updater;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.update_time
     *
     * @mbg.generated Mon Apr 26 20:05:47 JST 2021
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.user_id
     *
     * @return the value of user_info.user_id
     *
     * @mbg.generated Mon Apr 26 20:05:47 JST 2021
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.user_id
     *
     * @param userId the value for user_info.user_id
     *
     * @mbg.generated Mon Apr 26 20:05:47 JST 2021
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.user_name
     *
     * @return the value of user_info.user_name
     *
     * @mbg.generated Mon Apr 26 20:05:47 JST 2021
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.user_name
     *
     * @param userName the value for user_info.user_name
     *
     * @mbg.generated Mon Apr 26 20:05:47 JST 2021
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.password
     *
     * @return the value of user_info.password
     *
     * @mbg.generated Mon Apr 26 20:05:47 JST 2021
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.password
     *
     * @param password the value for user_info.password
     *
     * @mbg.generated Mon Apr 26 20:05:47 JST 2021
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.authority
     *
     * @return the value of user_info.authority
     *
     * @mbg.generated Mon Apr 26 20:05:47 JST 2021
     */
    public Integer getAuthority() {
        return authority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.authority
     *
     * @param authority the value for user_info.authority
     *
     * @mbg.generated Mon Apr 26 20:05:47 JST 2021
     */
    public void setAuthority(Integer authority) {
        this.authority = authority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.password_history
     *
     * @return the value of user_info.password_history
     *
     * @mbg.generated Mon Apr 26 20:05:47 JST 2021
     */
    public String getPasswordHistory() {
        return passwordHistory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.password_history
     *
     * @param passwordHistory the value for user_info.password_history
     *
     * @mbg.generated Mon Apr 26 20:05:47 JST 2021
     */
    public void setPasswordHistory(String passwordHistory) {
        this.passwordHistory = passwordHistory == null ? null : passwordHistory.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.description
     *
     * @return the value of user_info.description
     *
     * @mbg.generated Mon Apr 26 20:05:47 JST 2021
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.description
     *
     * @param description the value for user_info.description
     *
     * @mbg.generated Mon Apr 26 20:05:47 JST 2021
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.creater
     *
     * @return the value of user_info.creater
     *
     * @mbg.generated Mon Apr 26 20:05:47 JST 2021
     */
    public String getCreater() {
        return creater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.creater
     *
     * @param creater the value for user_info.creater
     *
     * @mbg.generated Mon Apr 26 20:05:47 JST 2021
     */
    public void setCreater(String creater) {
        this.creater = creater == null ? null : creater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.create_time
     *
     * @return the value of user_info.create_time
     *
     * @mbg.generated Mon Apr 26 20:05:47 JST 2021
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.create_time
     *
     * @param createTime the value for user_info.create_time
     *
     * @mbg.generated Mon Apr 26 20:05:47 JST 2021
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.updater
     *
     * @return the value of user_info.updater
     *
     * @mbg.generated Mon Apr 26 20:05:47 JST 2021
     */
    public String getUpdater() {
        return updater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.updater
     *
     * @param updater the value for user_info.updater
     *
     * @mbg.generated Mon Apr 26 20:05:47 JST 2021
     */
    public void setUpdater(String updater) {
        this.updater = updater == null ? null : updater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.update_time
     *
     * @return the value of user_info.update_time
     *
     * @mbg.generated Mon Apr 26 20:05:47 JST 2021
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.update_time
     *
     * @param updateTime the value for user_info.update_time
     *
     * @mbg.generated Mon Apr 26 20:05:47 JST 2021
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}