package org.innox.pojo;

import java.util.Date;

public class WordTable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column word_table.word_id
     *
     * @mbg.generated Wed May 12 16:37:06 JST 2021
     */
    private Long wordId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column word_table.word_name_translate
     *
     * @mbg.generated Wed May 12 16:37:06 JST 2021
     */
    private String wordNameTranslate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column word_table.word_name_orignal
     *
     * @mbg.generated Wed May 12 16:37:06 JST 2021
     */
    private String wordNameOrignal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column word_table.word_type
     *
     * @mbg.generated Wed May 12 16:37:06 JST 2021
     */
    private Object wordType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column word_table.description
     *
     * @mbg.generated Wed May 12 16:37:06 JST 2021
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column word_table.creater
     *
     * @mbg.generated Wed May 12 16:37:06 JST 2021
     */
    private String creater;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column word_table.create_time
     *
     * @mbg.generated Wed May 12 16:37:06 JST 2021
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column word_table.updater
     *
     * @mbg.generated Wed May 12 16:37:06 JST 2021
     */
    private String updater;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column word_table.update_time
     *
     * @mbg.generated Wed May 12 16:37:06 JST 2021
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column word_table.word_id
     *
     * @return the value of word_table.word_id
     *
     * @mbg.generated Wed May 12 16:37:06 JST 2021
     */
    public Long getWordId() {
        return wordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column word_table.word_id
     *
     * @param wordId the value for word_table.word_id
     *
     * @mbg.generated Wed May 12 16:37:06 JST 2021
     */
    public void setWordId(Long wordId) {
        this.wordId = wordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column word_table.word_name_translate
     *
     * @return the value of word_table.word_name_translate
     *
     * @mbg.generated Wed May 12 16:37:06 JST 2021
     */
    public String getWordNameTranslate() {
        return wordNameTranslate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column word_table.word_name_translate
     *
     * @param wordNameTranslate the value for word_table.word_name_translate
     *
     * @mbg.generated Wed May 12 16:37:06 JST 2021
     */
    public void setWordNameTranslate(String wordNameTranslate) {
        this.wordNameTranslate = wordNameTranslate == null ? null : wordNameTranslate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column word_table.word_name_orignal
     *
     * @return the value of word_table.word_name_orignal
     *
     * @mbg.generated Wed May 12 16:37:06 JST 2021
     */
    public String getWordNameOrignal() {
        return wordNameOrignal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column word_table.word_name_orignal
     *
     * @param wordNameOrignal the value for word_table.word_name_orignal
     *
     * @mbg.generated Wed May 12 16:37:06 JST 2021
     */
    public void setWordNameOrignal(String wordNameOrignal) {
        this.wordNameOrignal = wordNameOrignal == null ? null : wordNameOrignal.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column word_table.word_type
     *
     * @return the value of word_table.word_type
     *
     * @mbg.generated Wed May 12 16:37:06 JST 2021
     */
    public Object getWordType() {
        return wordType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column word_table.word_type
     *
     * @param wordType the value for word_table.word_type
     *
     * @mbg.generated Wed May 12 16:37:06 JST 2021
     */
    public void setWordType(Object wordType) {
        this.wordType = wordType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column word_table.description
     *
     * @return the value of word_table.description
     *
     * @mbg.generated Wed May 12 16:37:06 JST 2021
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column word_table.description
     *
     * @param description the value for word_table.description
     *
     * @mbg.generated Wed May 12 16:37:06 JST 2021
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column word_table.creater
     *
     * @return the value of word_table.creater
     *
     * @mbg.generated Wed May 12 16:37:06 JST 2021
     */
    public String getCreater() {
        return creater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column word_table.creater
     *
     * @param creater the value for word_table.creater
     *
     * @mbg.generated Wed May 12 16:37:06 JST 2021
     */
    public void setCreater(String creater) {
        this.creater = creater == null ? null : creater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column word_table.create_time
     *
     * @return the value of word_table.create_time
     *
     * @mbg.generated Wed May 12 16:37:06 JST 2021
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column word_table.create_time
     *
     * @param createTime the value for word_table.create_time
     *
     * @mbg.generated Wed May 12 16:37:06 JST 2021
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column word_table.updater
     *
     * @return the value of word_table.updater
     *
     * @mbg.generated Wed May 12 16:37:06 JST 2021
     */
    public String getUpdater() {
        return updater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column word_table.updater
     *
     * @param updater the value for word_table.updater
     *
     * @mbg.generated Wed May 12 16:37:06 JST 2021
     */
    public void setUpdater(String updater) {
        this.updater = updater == null ? null : updater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column word_table.update_time
     *
     * @return the value of word_table.update_time
     *
     * @mbg.generated Wed May 12 16:37:06 JST 2021
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column word_table.update_time
     *
     * @param updateTime the value for word_table.update_time
     *
     * @mbg.generated Wed May 12 16:37:06 JST 2021
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}